// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFolder(arg1:string,arg2:string):Promise<string>;

export function CreateTemplate(arg1:string,arg2:string):Promise<string>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function ExecuteTemplate(arg1:string,arg2:Record<string, string>):Promise<main.HTTPResponse>;

export function ExecuteTemplateWithOverrides(arg1:string,arg2:Record<string, string>):Promise<main.HTTPResponse>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetEnvironmentFilePath():Promise<string>;

export function GetHTTPMethods():Promise<Array<string>>;

export function GetOverrides():Promise<Record<string, string>>;

export function GetOverridesFilePath():Promise<string>;

export function GetTemplate(arg1:string):Promise<main.TemplateResponse>;

export function GetTemplates():Promise<Array<main.TemplateItem>>;

export function GetVariables():Promise<Record<string, any>>;

export function MoveItem(arg1:string,arg2:string):Promise<string>;

export function OpenEnvironmentFile():Promise<void>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenOverridesFile():Promise<void>;

export function RefreshVariables():Promise<Record<string, any>>;

export function ReloadConfig():Promise<void>;

export function RenameItem(arg1:string,arg2:string):Promise<string>;

export function SaveOverrides(arg1:Record<string, string>):Promise<void>;

export function SaveTemplate(arg1:string,arg2:string):Promise<void>;
