// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1, arg2) {
  return window['go']['app']['App']['CreateFolder'](arg1, arg2);
}

export function CreateTemplate(arg1, arg2) {
  return window['go']['app']['App']['CreateTemplate'](arg1, arg2);
}

export function DeleteTemplate(arg1) {
  return window['go']['app']['App']['DeleteTemplate'](arg1);
}

export function ExecuteTemplate(arg1, arg2) {
  return window['go']['app']['App']['ExecuteTemplate'](arg1, arg2);
}

export function ExecuteTemplateWithBodyAndOverrides(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteTemplateWithBodyAndOverrides'](arg1, arg2, arg3);
}

export function ExecuteTemplateWithOverrides(arg1, arg2) {
  return window['go']['app']['App']['ExecuteTemplateWithOverrides'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetEnvironmentFilePath() {
  return window['go']['app']['App']['GetEnvironmentFilePath']();
}

export function GetHTTPMethods() {
  return window['go']['app']['App']['GetHTTPMethods']();
}

export function GetOverrides() {
  return window['go']['app']['App']['GetOverrides']();
}

export function GetOverridesFilePath() {
  return window['go']['app']['App']['GetOverridesFilePath']();
}

export function GetTemplate(arg1) {
  return window['go']['app']['App']['GetTemplate'](arg1);
}

export function GetTemplates() {
  return window['go']['app']['App']['GetTemplates']();
}

export function GetVariables() {
  return window['go']['app']['App']['GetVariables']();
}

export function MoveItem(arg1, arg2) {
  return window['go']['app']['App']['MoveItem'](arg1, arg2);
}

export function OpenEnvironmentFile() {
  return window['go']['app']['App']['OpenEnvironmentFile']();
}

export function OpenInEditor(arg1) {
  return window['go']['app']['App']['OpenInEditor'](arg1);
}

export function OpenOverridesFile() {
  return window['go']['app']['App']['OpenOverridesFile']();
}

export function PreviewBody(arg1, arg2) {
  return window['go']['app']['App']['PreviewBody'](arg1, arg2);
}

export function PreviewTemplate(arg1, arg2) {
  return window['go']['app']['App']['PreviewTemplate'](arg1, arg2);
}

export function RefreshVariables() {
  return window['go']['app']['App']['RefreshVariables']();
}

export function ReloadConfig() {
  return window['go']['app']['App']['ReloadConfig']();
}

export function RenameItem(arg1, arg2) {
  return window['go']['app']['App']['RenameItem'](arg1, arg2);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveConfig'](arg1, arg2);
}

export function SaveOverrides(arg1) {
  return window['go']['app']['App']['SaveOverrides'](arg1);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['app']['App']['SaveTemplate'](arg1, arg2);
}
